### ISSUE TITLE
terraform-libvirt-windows-example - main.tf - Error

### ISSUE THREAD

**Issue by kevinwells22** [rgl/terraform-libvirt-windows-example#1]
Hi, I am set up on Ubuntu 20.04, installed Terraform, terraform-provider-libvirt, mkisofs, I have another terraform project running which creates Linux machines.
I am trying to run your 'terraform-libvirt-windows-example/blob/master/main.tf', but getting the below error.
Can you tell me what I am doing wrong please?

```
$ time terraform apply tfplan
libvirt_volume.example_root: Creating...
╷
│ Error: Can't retrieve base volume with name 'windows-2019-amd64_vagrant_box_image_0_box.img': Storage volume not found: no storage vol with matching name 'windows-2019-amd64_vagrant_box_image_0_box.img'
│ 
│   with libvirt_volume.example_root,
│   on main.tf line 169, in resource "libvirt_volume" "example_root":
│  169: resource "libvirt_volume" "example_root" {
│ 
╵
```

**Comment by rgl** [comment]
Oh, I forgot to mention in the README that you need to have the [windows 2019 base vagrant box installed](https://github.com/rgl/windows-vagrant).

Its now [easier to use the libvirt provider too](https://github.com/rgl/terraform-libvirt-ubuntu-example), but I still had no time to update this repo to reflect that.

**Comment by rgl** [comment]
This repository was updated to latest terraform, libvirt provider and now mentions the need to install the windows 2019 base vagrant box.
